# Generated by Django 5.1.1 on 2025-01-07 17:14

import froala_editor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_contact_first_name_alter_contact_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=froala_editor.fields.FroalaField(help_text='write your blog'),
        ),
    ]
